### PR TITLE
Update b4721eaf-e9d9-4839-bf42-5d36e790c23b

### PR DESCRIPTION
**Pull request by JoannaMcCaffrey**
Santa Barbara Botanic Garden - add recordset UUID

### CODE REVIEW

**Comment by JoannaMcCaffrey** [comment]
@kevinlove Travis is failing.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove I was wondering why there are still active branches - apparently I did this same edit 28 days ago and it was not integrated yet: Update b4721eaf-e9d9-4839-bf42-5d36e790c23b

**Comment by kevinlove** [comment]
@JoannaMcCaffrey I've restarted the build, but it keeps failing with this error:

"The command "tlmgr update --self" failed and exited with 25 during ."

This appears to be on the Travis side of things, but I can't find any documentation on the issue. We cannot make this merge until the system is back up, so please be patient as I monitor the situation with Travis.

As far as active branches go, you have 3 that I see:

https://github.com/iDigBio/idb-us-collections/compare/JoannaMcCaffrey-patch-2-1
https://github.com/iDigBio/idb-us-collections/compare/JoannaMcCaffrey-patch-2
https://github.com/iDigBio/idb-us-collections/compare/JoannaMcCaffrey-SBBG-1

These are branches that have never had a pull request created. That means that you edited the file and created the branch but never made a pull request. We need to work out a workflow for this situation, so if you have time, let's meet to discuss how we can resolve these branches and what to do in the future.

**Comment by kevinlove** [comment]
Looks like there is a ticket open on the Travis project about this issue:

https://github.com/travis-ci/travis-ci/issues/6139

When this is resolved, we can resume our workflow.

**Pull request merged**
