### PR TITLE
Update f2f50ab7-ac4a-430e-9c15-7e389a4bffdf

### PR DESCRIPTION
**Pull request by JoannaMcCaffrey**
conversation with Alex Van Dam - updated institution name, institution code, collection code, geographic range, lat, lon, spelling of Mayagüez and recordsets

### CODE REVIEW

**Comment by kevinlove** [comment]
@JoannaMcCaffrey, we need to connect Pull Requests to Issues when possible. This PR has an issue with action directly related to it:

Issue #166

**Comment by JoannaMcCaffrey** [comment]
OK, thanks for the reminder. Is it OK to merge this one now, superseding what ever changes were in #166?

**Comment by kevinlove** [comment]
@JoannaMcCaffrey:  #166 is just the documentation for what actions need to be taken, this PR is the actual changing of the data.

Looks like we also have some more data to fill in based on conversations with this user, like the new collection_lsid created in GRBIO, so let's not close the issue yet. We can continue to make update to this branch before we merge them. I'll go ahead and add the LSID now and close the PR when we have completed all of the requested action in the original ticket.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove this is the dataset in GBIF: http://www.gbif.org/publisher/45346344-bad3-4a45-8563-98955464b3ca

**Pull request merged**
