### PR TITLE
Update 60e28f81-e634-4869-aa3e-732caed713c8

### PR DESCRIPTION
**Pull request by JoannaMcCaffrey**
National Museum of Natural History, Smithsonian Institution: add recordsetID, changed institution code/collection code to match data.

### CODE REVIEW

**Comment by kevinlove** [comment]
Please don't merge this change:

https://github.com/iDigBio/idb-us-collections/issues/181

**Comment by JoannaMcCaffrey** [comment]
What Larry D. sent is not what is in the data:
https://beta-portal.idigbio.org/portal/recordsets/3f1100f3-c4be-4c94-af61-bd0d2d011b8a
I'll ask Larry and Rusty what gives.

**Comment by kevinlove** [comment]
before you do that , let's chat via telephone

**Comment by kevinlove** [comment]
Closing without merging.

**Pull request closed without merging**
