### PR TITLE
Update 3ee20a40-cb46-40a4-aaa0-09f7cbe0eaaf

### PR DESCRIPTION
**Pull request by JoannaMcCaffrey**
Added collectionCode and containing types = true

### CODE REVIEW

**Comment by JoannaMcCaffrey** [comment]
@kevinlove Could you please check this out and let me know what is wrong. I thought I did the boolean correctly, so what is wrong?

**Comment by kevinlove** [comment]
Looks like Travis errored, no issues with your committ that I could see. I restarted the build and it looks like it completed fine.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove it still looks like in error from my desk.

**Comment by kevinlove** [comment]
@JoannaMcCaffrey Travis looks like its was having some serious issues with this PR. I verified the changes have been committed and am going to close out this PR. Let's monitor the next change closely to see if have the same issue.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove The KnownToContainTypes field did not fill correctly:
https://www.idigbio.org/portal/collections/3ee20a40-cb46-40a4-aaa0-09f7cbe0eaaf
I'm pretty sure my edit said 'true' - without quotes.

**Comment by kevinlove** [comment]
@JoannaMcCaffrey You have the correct value in the data, the portal is just not showing it correctly:

https://github.com/iDigBio/idb-us-collections/blob/master/collections/3ee20a40-cb46-40a4-aaa0-09f7cbe0eaaf

**Pull request merged**
